### ISSUE TITLE
Refueling only goes up to 18 & stops

### ISSUE THREAD

**Issue by cantresist** [Fragtality/WorkingTitle2GSX#4]
Okay so i got it working now but when i call gsx to refuel and the truck comes the fuel goes up to 18% & just stops after that..

I imported my fuel only after gsx requested me to do so, i did, it went up to 18% and just stopped.

**Comment by Fragtality** [comment]
Do read the Readme.

**Comment by cantresist** [comment]
I did.

**Comment by Fragtality** [comment]
> I imported my fuel only after gsx requested me to do so

Tells me you did not.

**Comment by cantresist** [comment]
What, i literally did. Not only today but also when i was having the installer issue.

**Comment by Fragtality** [comment]
Well, your Installer Issue was you not clicking on a Link on the 4th Paragraph of the Readme (like on the very top). So it is bit hard to believe that my Tool is currently doing something wrong, you know?

Especially when what your reporting now sounds like something which will exactly happen like that, if you did not take the necessary Steps explained in the Readme. (I can only guess what you're meaning, because you somehow refuse to give any useful Information.)

So before we take this any further, please provide:
- Screenshot of the "Customize Aircraft" Dialog of GSX
- Screenshot of your GSX Settings
- The Logs from `%appdata%\WorkingTitle2GSX\log`

**Comment by cantresist** [comment]
[WorkingTitle2GSX20240517.log](https://github.com/Fragtality/WorkingTitle2GSX/files/15358856/WorkingTitle2GSX20240517.log)
![Screenshot 2024-05-17 200048](https://github.com/Fragtality/WorkingTitle2GSX/assets/148928020/72b7ed20-abe8-4608-a827-2390b4935970)
![Screenshot 2024-05-17 200012](https://github.com/Fragtality/WorkingTitle2GSX/assets/148928020/efc3b879-446c-46c6-aa18-150d70c2b9c3)

**Comment by cantresist** [comment]
Im dumb, and im sorry gang. Misread payload for fuel.. 
![istockphoto-543347592-612x612](https://github.com/Fragtality/WorkingTitle2GSX/assets/148928020/deed7a35-df15-4680-9a64-292448d970b6)

**Comment by Fragtality** [comment]
Ah okay, would not have seen any Problems in the Log anyway - did what was planned in the Simbrief OFP.
(Note that the Tool does Fuel- as well as Payload-Synchronization)

Still don't know where you picked up that Percentage. Maybe from the MSFS Dialog? That would have been the wrong Place anyway - what is important is what the Airplane Systems are reporting.
